name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.27.1
      - name: Build Packages
        run: |
          pnpm i
          pnpm build
      - name: Build and Test Examples
        run: |
          cd examples/workspace
          npm run build:all
          npm run test:all
